site_name: Flaker
repo_name: Flaker
repo_url: https://github.com/rotbolt/flaker
edit_uri: edit/main/docs/
site_description: " A flaky network simulator for your mobile app development."
site_author: Rotbolt
remote_branch: gh-pages
nav:
  - Overview: index.md
  - Getting Started: getting-started.md
  - Development: development.md
theme:
  name: 'material'
  favicon: assets/logo.png
  logo: assets/logo.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: blue
      toggle:
        icon: octicons/sun-24
        name: "Switch to Dark Mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: blue
      toggle:
        icon: octicons/moon-24
        name: "Switch to Light Mode"
  features:
    - navigation.tabs
markdown_extensions:
  - attr_list
  - md_in_html

