site_name: Flaker
repo_name: Flaker
repo_url: https://github.com/rotbolt/flaker
edit_uri: edit/main/docs/
site_description: " A flaky network simulator for your mobile app development."
site_author: Rotbolt
remote_branch: gh-pages
nav:
  - Overview: index.md
  - Getting Started: getting-started.md
  - Development: development.md
theme:
  name: 'material'
  logo: 'assets/logo.png'
  icon:
    repo: fontawesome/brands/github
  favicon: 'assets/logo.png'
  palette:
    primary: 'deep-orange'
    accent: 'deep-purple'
markdown_extensions:
  - attr_list
  - md_in_html

