site_name: Flaker
repo_name: Flaker
repo_url: https://github.com/rotbolt/flaker
edit_uri: edit/main/docs/
site_description: " A flaky network simulator for your mobile app development."
site_author: Rotbolt
remote_branch: gh-pages
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Development: development.md
theme: material
markdown_extensions:
  - attr_list
  - md_in_html

