name: flaker-ci
run-name: flaker CI
on: [push]
jobs:
  projectbuild:
    name: Project build and tests
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Inject Secrets
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: |
          touch secrets.properties
          echo "SENTRY_DSN = $SENTRY_DSN" >> secrets.properties

      - name: Run detekt
        run: bash ./gradlew detekt

      - name: Run detekt iOS
        run: bash ./gradlew detektMetadataIosMain

      - name: Run detekt common
        run: bash ./gradlew detektMetadataCommonMain && ./gradlew detektMetaDataMain

      - name: Run Unit tests
        run: bash ./gradlew test --stacktrace
